name: Butter
version: ${project.version}
main: me.stevenlol.butter.Main
api-version: 1.16
depend: [ Vault ]
authors: [ stevenlol ]
description: Butter, designed and programmed for Minecraft 1.16+
commands:
  global:
    description: Set channel to global chat.
    aliases: ["g"]
  staff:
    description: Set channel to staff chat.
  mute:
    description: Mute a player.
    aliases: ["punish"]

permissions:
  butter:
    moderation:
      mute:
        default: false
    channel:
      global:
        default: true
      staff:
        default: false