name: Butter
version: ${project.version}
main: me.stevenlol.butter.Main
api-version: 1.16
depend: [ Vault ]
authors: [ stevenlol ]
description: Butter, designed and programmed for Minecraft 1.16+
commands:
permissions:
