name: Butter
version: ${project.version}
main: me.stevenlol.butter.Main
api-version: 1.16
depend: [ Vault ]
authors: [ stevenlol ]
description: Butter, designed and programmed for Minecraft 1.16+
commands:
  global:
    description: Set channel to global chat.
    aliases: ["g"]
  staff:
    description: Set channel to staff chat.
  mute:
    description: Mute a player.
    aliases: ["punish"]
  unmute:
    description: Unmute a player.
    aliases: ["unpunish"]
  ban:
    description: Ban a player.
  unban:
    description: Un-bans a player

permissions:
  butter:
    moderation:
      mute:
        default: false
      unmute:
        default: false
      ban:
        default: false
      unban:
        default: false
    channel:
      global:
        default: true
      staff:
        default: false